name: Generate Daily Reddit Report

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 8 * * *' # 每天UTC时间早上8点运行 (北京时间下午4点)

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Analysis Script
        env:
             REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
             REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: python scripts/analyze.py

      - name: Commit and Push Report
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: 自动更新每日趋势报告"
          file_pattern: "output/* report.md" # 提交output文件夹和根目录的report.md
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
